### ISSUE TITLE
Sizes of tensors must match except in dimension 0. Expected size 1280 but got size 768 for tensor number 1 in the list

### ISSUE THREAD

**Issue by DogeWowSuch** [nullquant/ComfyUI-BrushNet#53] opened 2024-05-04 06:16 UTC
Hit error upon latest update (as of 4th May 2024)

```
Error occurred when executing BrushNet:

Sizes of tensors must match except in dimension 0. Expected size 1280 but got size 768 for tensor number 1 in the list.

  File "D:\AI\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 274, in model_update
    add_text_embeds2 = torch.cat([negative_pooled_prompt_embeds, add_text_embeds], dim=0)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

**Comment by nullquant** [comment] 2024-05-04 09:37
What CLIP do you use?

**Comment by ZongrongLi** [comment] 2024-05-12 18:32
@nullquant  
it turned out the prompt can not be too long ,
I met this error with this prompt:
```
masterpiece, phot-relistic:1.4, RAW photo, absurdreshyperdetailed, realistic, Foreground blur:1.3, Deep Shadow, high contrast, professional photography photos, best quality, 8k1girl, solo, long hair, looking at viewer, black hair, dress, bare shoulders, jewelry, flower, earrings, outdoors, parted lips
```
but if I delete the last one ` parted lips`, there is no problem.

**Comment by nullquant** [comment] 2024-05-16 20:11
Closed as duplicate of the issue https://github.com/nullquant/ComfyUI-BrushNet/issues/89

**Closed by nullquant** 2024-05-16 20:11 UTC
Labels: bug
